# ~/.config/mpd/mpd.conf

music_directory "/home/axelnixos/Música"
playlist_directory "/home/axelnixos/.config/mpd/playlists"
db_file "/home/axelnixos/.config/mpd/database"
log_file "/home/axelnixos/.config/mpd/log"
pid_file "/home/axelnixos/.config/mpd/pid"
state_file "/home/axelnixos/.config/mpd/state"
sticker_file "/home/axelnixos/.config/mpd/sticker.sql"

follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"
auto_update             "yes"
#bind_to_address    "127.0.0.1:6600"
restore_paused      "yes"
max_output_buffer_size "16384"

# Audio output para PipeWire
audio_output {
      type "pipewire"
      name "PipeWire Output"
      mixer_type "software"
}

# FIFO para el visualizador (Cava)
audio_output {
    type    "fifo"
    name    "FIFO for visualizer"
    path    "/tmp/mpd.fifo"
    format  "44100:16:2"
}
